export interface SeedPlace {
  title: string;
  originalName: string;
  category: 'buda' | 'pest' | 'termas' | 'ruin-bars' | 'cultura' | 'miradores';
  description: string;
  visited: boolean;
  priority: 'imprescindible' | 'recomendado' | 'opcional';
  estimatedTimeMinutes: number;
  locationName: string;
  googleMapsQuery: string;
  tip: string;
}

export const BUDAPEST_SEED_PLACES: SeedPlace[] = [
  {
    title: "Money Exchange",
    originalName: "Valutaváltó (Exclusive Change / Correct Change)",
    category: "pest",
    description: "Oficina de cambio de divisas (4,3★ con 601 reseñas). Clave para conseguir florines húngaros (HUF) con tipo de cambio oficial competitivo y sin comisiones abusivas.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 15,
    locationName: "Váci utca / Deák Ferenc tér, Pest",
    googleMapsQuery: "Money Exchange Budapest",
    tip: "Evita los cajeros automáticos amarillos y azules de Euronet por sus comisiones elevadas. Busca siempre casas con cartel transparente de compra/venta como Correct Change."
  },
  {
    title: "Souvenir and Coffee / Department of Travel",
    originalName: "Souvenir and Coffee / Department of Travel",
    category: "pest",
    description: "Tienda de recuerdos de autor y cafetería de especialidad con valoración perfecta (5,0★ con 1.403 reseñas). Postales artísticas, artesanía húngara y excelente café.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 30,
    locationName: "Centro de Pest",
    googleMapsQuery: "Souvenir and Coffee Department of Travel Budapest",
    tip: "El sitio perfecto para llevarte recuerdos auténticos y diseñados por creadores locales, huyendo de los souvenirs industriales genéricos."
  },
  {
    title: "Dob u. 74",
    originalName: "Dob utca 74, 1073 Budapest",
    category: "pest",
    description: "Punto neurálgico y alojamiento en el corazón del Barrio Judío (Erzsébetváros, Distrito VII). A poca distancia de los mejores restaurantes, plazas y ruin bars.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 20,
    locationName: "Dob u. 74, 1073 Budapest, Hungría",
    googleMapsQuery: "Dob u. 74 Budapest 1073 Hungary",
    tip: "Ubicación inmejorable: estás a 5 minutos a pie de la Gran Sinagoga, el pasaje Gozsdu Udvar y la parada de tranvía 4/6 en Király utca."
  },
  {
    title: "Comida callejera Karaván",
    originalName: "Street Food Karaván Budapest",
    category: "pest",
    description: "Patio gastronómico al aire libre con food trucks (4,3★ con 12.284 reseñas; 4000-6000 Ft). Hamburguesas de lángos, goulash servido en hogaza de pan y bocados húngaros.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 45,
    locationName: "Kazinczy u. 18, 1075 Budapest",
    googleMapsQuery: "Karaván Budapest Kazinczy u. 18",
    tip: "Prueba el famoso 'Lángos Burger' de Paneer o los tradicionales Kürtőskalács recién hechos. Situado justo al lado del mítico Szimpla Kert."
  },
  {
    title: "Gran Sinagoga de Budapest",
    originalName: "Dohány utcai zsinagóga",
    category: "cultura",
    description: "La sinagoga más grande de Europa y 2ª del mundo (4,3★ con 29.821 reseñas). De estilo morisco-bizantino, con el sauce llorón de acero conmemorativo y museo judío.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 75,
    locationName: "Dohány u. 2, 1074 Budapest",
    googleMapsQuery: "Dohány Street Synagogue Budapest",
    tip: "Recuerda que los viernes por la tarde y los sábados está cerrada por Shabat. Los hombres deben llevar la cabeza cubierta (entregan kipá en la entrada)."
  },
  {
    title: "Instant-Fogas Complex",
    originalName: "Instant-Fogas Ház",
    category: "ruin-bars",
    description: "El macro-complejo de discotecas y bares en ruina más grande de Budapest (4,3★ con 17.351 reseñas; 2000-12.000 Ft). Más de 7 salas con música techno, r&b, indie y patios decorados.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 120,
    locationName: "Akácfa u. 51, 1073 Budapest",
    googleMapsQuery: "Instant-Fogas Complex Budapest",
    tip: "Entrada habitualmente libre a primera hora. Piérdete por las distintas plantas para descubrir sus habitaciones surrealistas con animales gigantes suspendidos."
  },
  {
    title: "The Magic Budapest",
    originalName: "The Magic Castle Restaurant",
    category: "pest",
    description: "Restaurante y cocktail bar temático de fantasía y magia estilo Hogwarts (4,6★ con 19.487 reseñas; 6000-16.000 Ft). Pociones humeantes con hielo seco y hamburguesas encantadas.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 90,
    locationName: "Hajós u. 25, 1065 Budapest",
    googleMapsQuery: "The Magic Budapest Hajós u. 25",
    tip: "Imprescindible reservar con antelación desde su web si vas en horario de cena o fin de semana. Prueba alguna de las pociones con efecto de niebla."
  },
  {
    title: "Aeropuerto de Budapest-Ferenc Liszt",
    originalName: "Budapest Liszt Ferenc Nemzetközi Repülőtér",
    category: "pest",
    description: "Principal aeropuerto internacional de Hungría (4,1★ con 39.449 reseñas). Puerta de entrada y salida del viaje.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 60,
    locationName: "1185 Budapest",
    googleMapsQuery: "Budapest Ferenc Liszt International Airport",
    tip: "El autobús exprés 100E conecta las terminales directamente con Deák Ferenc tér (centro) en unos 35-45 minutos por unos 2.200 HUF."
  },
  {
    title: "Moon Budapest",
    originalName: "Moon Budapest Cocktail Bar",
    category: "ruin-bars",
    description: "Lounge bar moderno y cosmopolita en el bullicioso pasaje peatonal Gozsdu Udvar (4,6★ con 895 reseñas). Cócteles de autor, iluminación tenue y música actual.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 60,
    locationName: "Holló u. 1, 1075 Budapest (Gozsdu Udvar)",
    googleMapsQuery: "Moon Budapest Holló u. 1",
    tip: "Ideal para tomar la primera copa en un entorno sofisticado antes de adentrarse en la noche del barrio judío."
  },
  {
    title: "Monumento al príncipe de Buda y la princesa de Pest",
    originalName: "Buda királyfi és Pest királykisasszony",
    category: "miradores",
    description: "Tierna escultura de bronce en el mirador del Jardín de los Filósofos (4,6★ con 653 reseñas). Representa el encuentro sobre el río entre Buda y Pest.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 30,
    locationName: "Colina Gellért (Filozófusok kertje), Buda",
    googleMapsQuery: "Buda Prince and Pest Princess statue Budapest",
    tip: "Uno de los secretos mejor guardados de la Colina Gellért: banco con vistas abiertas hacia el Castillo y el Danubio sin aglomeraciones de turistas."
  },
  {
    title: "Bares en ruina Budapest",
    originalName: "Romkocsmák (Szimpla Kert & Barrio Judío)",
    category: "ruin-bars",
    description: "La experiencia nocturna insignia de Budapest (4,6★ con 7.844 reseñas; 2000-10.000 Ft). Locales bohemios creados en edificios abandonados con arte reciclado y jardines interiores.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 90,
    locationName: "Kazinczy utca / Erzsébetváros, Pest",
    googleMapsQuery: "Szimpla Kert Budapest Kazinczy u. 14",
    tip: "Pide una jarra de cerveza artesanal local o un 'Fröccs' (vino húngaro con soda artesanal). Los domingos por la mañana organizan un mercado ecológico."
  },
  {
    title: "Casa del Terror",
    originalName: "Terror Háza Múzeum",
    category: "cultura",
    description: "Museo conmemorativo en la señorial avenida Andrássy (4,1★ con 24.573 reseñas). Antigua sede de la policía secreta durante los regímenes nazi y comunista, con celdas intactas en el sótano.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 120,
    locationName: "Andrássy út 60, 1062 Budapest",
    googleMapsQuery: "House of Terror Budapest Andrássy út 60",
    tip: "Alquila la audioguía en español en taquilla para comprender todo el contexto de los acontecimientos y los testimonios de los supervivientes."
  },
  {
    title: "Colina Gellért",
    originalName: "Gellért-hegy",
    category: "miradores",
    description: "Colina de 235 metros frente al Danubio (4,7★ con 2.712 reseñas). Ofrece las vistas panorámicas más deslumbrantes de los puentes, el Parlamento y la cuenca de Pest.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 90,
    locationName: "Gellért-hegy, 1118 Budapest, Buda",
    googleMapsQuery: "Gellért Hill Budapest",
    tip: "Sube a pie por el sendero que nace al lado del Hotel Gellért pasando por la Iglesia en la Roca (Sziklatemplom) al atardecer."
  },
  {
    title: "McDonald's Nyugati",
    originalName: "McDonald's Nyugati pályaudvar",
    category: "pest",
    description: "Considerado el McDonald's más bello y elegante del mundo (4,1★ con 12.755 reseñas; 2000-4000 Ft). Construido en el ala colonial de la estación de tren diseñada por la compañía de Gustave Eiffel en 1877.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 30,
    locationName: "Teréz krt. 55, 1062 Budapest",
    googleMapsQuery: "McDonald's Nyugati Budapest Teréz krt",
    tip: "Pásate aunque sea a tomar un café McCafé para contemplar sus techos con estucos barrocos, columnas de hierro y lámparas de araña decimonónicas."
  },
  {
    title: "Pop&Roll Art Toilet",
    originalName: "Pop&Roll Art Toilet",
    category: "pest",
    description: "Curioso espacio de arte pop, diseño de vanguardia y baños temáticos inmersivos (4,5★ con 571 reseñas). Una parada fotogénica y original en la calle comercial.",
    visited: false,
    priority: "opcional",
    estimatedTimeMinutes: 20,
    locationName: "Váci u. 19-21, 1052 Budapest",
    googleMapsQuery: "Pop&Roll Art Toilet Budapest Váci u",
    tip: "Ideal para una foto diferente y como alternativa artística de descanso en plena calle peatonal Váci utca."
  },
  {
    title: "Museo de Aquincum",
    originalName: "Aquincumi Múzeum és Régészeti Park",
    category: "cultura",
    description: "Yacimiento arqueológico romano al aire libre de la antigua capital de Panonia (4,6★ con 2.749 reseñas). Ruinas de anfiteatro, mosaicos romanos, basílica civil y el órgano hidráulico.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 90,
    locationName: "Szentendrei út 135, 1031 Budapest (Óbuda)",
    googleMapsQuery: "Aquincum Museum Budapest Szentendrei út",
    tip: "Se llega muy rápido tomando el tren de cercanías suburbano HÉV (H5) desde la estación Batthyány tér."
  },
  {
    title: "Barco Cultural A38",
    originalName: "A38 Hajó",
    category: "ruin-bars",
    description: "Antiguo barco carguero ucraniano de piedra reconvertido en club y sala de conciertos flotante sobre el Danubio (4,5★ con 9.039 reseñas). Galardonado como uno de los mejores clubes del mundo.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 90,
    locationName: "Petőfi híd budai hídfő, 1117 Budapest",
    googleMapsQuery: "A38 Ship Budapest Petőfi híd",
    tip: "La terraza en la cubierta del barco es un lugar idílico para tomar algo al aire libre mirando el reflejo de las luces en el Danubio."
  },
  {
    title: "Smashy Burger Budapest",
    originalName: "smashy burger | budapest",
    category: "pest",
    description: "Hamburguesería de culto especializada en smash burgers ultracrujientes con pan brioche artesano y carne madurada (4,7★ con 11.822 reseñas; 2000-4000 Ft).",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 40,
    locationName: "Madách Imre út 12, 1075 Budapest",
    googleMapsQuery: "smashy burger budapest Madách Imre út",
    tip: "Pide la Doble Cheeseburger con salsa de la casa. Servicio rápido en pleno eje gastronómico de Madách Imre tér."
  },
  {
    title: "Puente de las Cadenas",
    originalName: "Széchenyi Lánchíd",
    category: "pest",
    description: "El puente colgante más antiguo y famoso que unió Buda y Pest en 1849 (4,7★ con 65.013 reseñas). Custodiado por los imponentes leones de piedra del escultor Marschalkó.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 30,
    locationName: "Széchenyi Lánchíd, sobre el Danubio",
    googleMapsQuery: "Széchenyi Chain Bridge Budapest",
    tip: "Cruzarlo caminando de noche mientras el Castillo de Buda y el Parlamento están iluminados es una de las postales más imborrables del viaje."
  },
  {
    title: "Iguana Bar and Grill",
    originalName: "Iguana Bar & Grill",
    category: "pest",
    description: "Clásico y vibrante restaurante mexicano cerca de la Plaza de la Libertad y el Parlamento (4,6★ con 7.962 reseñas; 6000-14.000 Ft). Tacos, quesadillas, fajitas y margaritas heladas.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 60,
    locationName: "Zoltán u. 16, 1054 Budapest",
    googleMapsQuery: "Iguana Bar and Grill Budapest Zoltán u",
    tip: "Excelente opción para cenar comida sabrosa y generosa tras visitar el Parlamento y la Plaza de la Libertad."
  },
  {
    title: "Plaza de la Libertad",
    originalName: "Szabadság tér",
    category: "pest",
    description: "Una de las plazas más majestuosas y cargadas de historia de Pest (4,0★ con 1.871 reseñas). Rodeada por palacios modernistas, el Monumento Soviético y la estatua de Ronald Reagan.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 40,
    locationName: "Szabadság tér, 1054 Budapest",
    googleMapsQuery: "Szabadság tér Budapest",
    tip: "Busca con atención en las barandillas de hierro la diminuta y simpática estatua de bronce de la Rana Gustavo (Kermit) esculpida por Mihály Kolodko."
  },
  {
    title: "Centro Comercial Westend",
    originalName: "Westend Bevásárlóközpont",
    category: "pest",
    description: "Gran centro comercial junto a la estación Nyugati (4,5★ con 1.123 reseñas). Con más de 400 tiendas, terraza ajardinada en la azotea, cines y amplia zona de restauración.",
    visited: false,
    priority: "opcional",
    estimatedTimeMinutes: 60,
    locationName: "Váci út 1-3, 1062 Budapest",
    googleMapsQuery: "Westend Shopping Center Budapest Váci út",
    tip: "Muy útil si necesitas comprar cualquier artículo de viaje, ropa o hacer compras a cubierto."
  },
  {
    title: "Jardín Japonés (Isla Margarita)",
    originalName: "Japánkert - Margitsziget",
    category: "cultura",
    description: "Jardín zen tradicional creado en la parte norte de la Isla Margarita (4,5★ con 2.141 reseñas). Con estanques con peces koi, puentecito de madera, nenúfares y cascada natural.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 45,
    locationName: "Isla Margarita (Margitsziget), 1138 Budapest",
    googleMapsQuery: "Japanese Garden Margaret Island Budapest",
    tip: "Alquila una bicicleta o un carrito 'bringóhintó' para recorrer toda la Isla Margarita desde la Fuente Musical hasta el Jardín Japonés."
  },
  {
    title: "Mercado Central de Budapest",
    originalName: "Nagy Vásárcsarnok",
    category: "pest",
    description: "El mercado cubierto más impresionante del siglo XIX con tejas de cerámica de Zsolnay (4,3★ con 123.441 reseñas). Puestos de pimentón paprika, embutidos y comida tradicional húngara.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 75,
    locationName: "Vámház krt. 1-3, 1093 Budapest",
    googleMapsQuery: "Great Market Hall Budapest",
    tip: "Cerrado los domingos. Sube a la primera planta para probar los auténticos Lángos húngaros y comprar souvenirs típicos de madera y bordados."
  },
  {
    title: "Basílica de San Esteban",
    originalName: "Szent István-bazilika",
    category: "pest",
    description: "La iglesia más grande y majestuosa de Budapest con 96 metros de cúpula (4,7★ con 79.982 reseñas). Custodia la reliquia sagrada de la mano incorrupta del primer rey húngaro.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 60,
    locationName: "Szent István tér 1, 1051 Budapest",
    googleMapsQuery: "St. Stephen's Basilica Budapest",
    tip: "Sube a la galería exterior de la cúpula (hay ascensor) para disfrutar de una vista panorámica circular de 360 grados de toda la ciudad."
  },
  {
    title: "La Ciudadela",
    originalName: "Citadella",
    category: "miradores",
    description: "Fortaleza militar erigida en 1854 en el punto más alto de la Colina Gellért (4,6★ con 22.529 reseñas). Coronada por la célebre Estatua de la Libertad de 14 metros con la hoja de palma.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 60,
    locationName: "Citadella sétány, 1118 Budapest, Buda",
    googleMapsQuery: "Citadella Budapest Gellért Hill",
    tip: "El mirador definitivo para tomar fotos de postal de los 8 puentes que cruzan el Danubio y toda la llanura de Pest."
  },
  {
    title: "Galería Nacional Húngara",
    originalName: "Magyar Nemzeti Galéria",
    category: "buda",
    description: "El museo de arte más importante del país, situado en las dependencias del Palacio Real de Buda (4,7★ con 11.255 reseñas). Retablos góticos, pintura del siglo XIX y escultura húngara.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 90,
    locationName: "Szent György tér 2, 1014 Budapest (Castillo de Buda)",
    googleMapsQuery: "Hungarian National Gallery Buda Castle",
    tip: "La entrada incluye el acceso a la cúpula central del Palacio Real, desde donde hay una perspectiva privilegiada del Puente de las Cadenas."
  },
  {
    title: "Bastión de los Pescadores",
    originalName: "Halászbástya",
    category: "buda",
    description: "Monumento de ensueño neorrománico con 7 torres cónicas que representan a las tribus magiares fundadoras (4,8★ con 117.257 reseñas). El mirador más fotografiado de Europa.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 60,
    locationName: "Szentháromság tér, 1014 Budapest (Distrito del Castillo)",
    googleMapsQuery: "Fisherman's Bastion Budapest",
    tip: "El mirador inferior es siempre de acceso libre y gratuito las 24 horas. Visítalo al amanecer para sacar fotos sin multitudes frente al Parlamento."
  },
  {
    title: "Centro Comercial Mammut",
    originalName: "Mammut Bevásárló Központ",
    category: "buda",
    description: "El principal complejo comercial y de ocio del lado de Buda (4,2★ con 36.752 reseñas). Dos grandes edificios conectados por pasarelas con cines, cafeterías y tiendas de moda.",
    visited: false,
    priority: "opcional",
    estimatedTimeMinutes: 45,
    locationName: "Lövőház u. 2-6, 1024 Budapest (Széll Kálmán tér)",
    googleMapsQuery: "Mammut Shopping Center Budapest",
    tip: "Ubicado junto al animado parque Millenáris y el mercado gastronómico tradicional de Fény utca."
  },
  {
    title: "Reserva Natural Ördög-orom",
    originalName: "Ördög-orom Természetvédelmi Terület",
    category: "miradores",
    description: "Reserva natural protegida sobre formaciones rocosas de dolomita (4,8★ con 287 reseñas). Rutas de senderismo y vistas panorámicas agrestes de los valles del suroeste de Buda.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 90,
    locationName: "Edvi Illés út, 1112 Budapest, Buda",
    googleMapsQuery: "Ördög-orom Budapest Természetvédelmi Terület",
    tip: "Lleva zapatillas con buen agarre para recorrer los senderos señalizados de la cresta rocosa al atardecer."
  },
  {
    title: "Castillo de Vajdahunyad",
    originalName: "Vajdahunyad vára",
    category: "cultura",
    description: "Castillo romántico de fantasía en el Parque de la Ciudad (4,7★ con 27.389 reseñas). Réplica del castillo de Hunyad en Transilvania que conjuga estilos románico, gótico y renacentista.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 60,
    locationName: "Vajdahunyad stny., 1146 Budapest (Városliget)",
    googleMapsQuery: "Vajdahunyad Castle Budapest",
    tip: "Visita la estatua de bronce de 'Anonymus' en el patio: la leyenda dice que tocar su pluma de escribir concede inspiración y buena fortuna."
  },
  {
    title: "Teatro de Opereta de Budapest",
    originalName: "Budapesti Operettszínház",
    category: "cultura",
    description: "Teatro histórico de 1894 en la 'calle de los teatros' Nagymező utca (4,8★ con 10.906 reseñas). Cuna de las grandes obras de opereta de Emmerich Kálmán y musicales internacionales.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 90,
    locationName: "Nagymező u. 17, 1065 Budapest",
    googleMapsQuery: "Budapest Operetta Theatre Nagymező u",
    tip: "La calle Nagymező utca cuenta con numerosos cafés y terrazas bohemias ideales para tomar algo antes o después del teatro."
  },
  {
    title: "Ópera Nacional de Hungría",
    originalName: "Magyar Állami Operaház",
    category: "cultura",
    description: "Obra cumbre neorrenacentista de Miklós Ybl en la avenida Andrássy (4,7★ con 24.532 reseñas). Considerada una de las salas con acústica más perfecta del mundo.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 60,
    locationName: "Andrássy út 22, 1061 Budapest",
    googleMapsQuery: "Hungarian State Opera Budapest Andrássy út",
    tip: "Se ofrecen tours guiados en español por la tarde que suelen incluir un mini concierto en directo en la gran escalera de mármol."
  },
  {
    title: "Zapatos en la Orilla del Danubio",
    originalName: "Cipők a Duna-parton",
    category: "pest",
    description: "Sobrecogedor monumento conmemorativo con 60 pares de zapatos de hierro forjado al borde del agua (4,7★ con 26.876 reseñas). Homenaje a las víctimas fusiladas en 1944-1945.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 25,
    locationName: "Id. Antall József rkp., a 300m del Parlamento",
    googleMapsQuery: "Shoes on the Danube Bank Budapest",
    tip: "Lugar de máximo respeto y silencio. La luz del atardecer reflejándose en el Danubio le confiere un impacto visual y emotivo extraordinario."
  },
  {
    title: "Monumento del Milenio (Plaza de los Héroes)",
    originalName: "Millenniumi emlékmű - Hősök tere",
    category: "cultura",
    description: "Conjunto monumental erigido en 1896 para celebrar los mil años de la nación húngara (4,7★ con 2.914 reseñas). Columna con el arcángel Gabriel flanqueada por las estatuas de los reyes.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 45,
    locationName: "Hősök tere, 1146 Budapest",
    googleMapsQuery: "Heroes' Square Budapest",
    tip: "Llega tomando la línea de metro M1 (Földalatti), la primera línea subterránea de Europa continental, declarada Patrimonio de la Humanidad."
  },
  {
    title: "Parlamento de Budapest",
    originalName: "Országház",
    category: "pest",
    description: "El edificio neogótico más icónico de Hungría a orillas del río Danubio (4,8★ con 30.523 reseñas). Con 691 estancias, la Gran Escalera dorada y la Corona de San Esteban.",
    visited: false,
    priority: "imprescindible",
    estimatedTimeMinutes: 90,
    locationName: "Kossuth Lajos tér 1-3, 1055 Budapest",
    googleMapsQuery: "Hungarian Parliament Building Budapest",
    tip: "Reserva tu entrada y visita guiada en español con antelación en el portal oficial jegymester.hu para evitar quedarte sin plaza."
  },
  {
    title: "Casa de las Mariposas",
    originalName: "Lepkeház (Városliget)",
    category: "cultura",
    description: "Invernadero botánico tropical con cientos de mariposas vivas revoloteando entre orquídeas y vegetación selvática (4,6★ con 45 reseñas).",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 40,
    locationName: "Állatkerti krt. 6-12, 1146 Budapest (Városliget)",
    googleMapsQuery: "Butterfly House Budapest Zoo",
    tip: "Viste prendas amarillas o de colores vivos para que las mariposas se posen en tus brazos o hombros para sacar fotos cercanas."
  },
  {
    title: "Tropicarium-Oceanarium Kft.",
    originalName: "Tropicarium - A cápás állatkert",
    category: "cultura",
    description: "El acuario marino con tiburones más grande de Centroeuropa (4,5★ con 33.611 reseñas). Túnel subacuático acrílico de 12 metros, sala de lluvia tropical con caimanes y rayas.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 90,
    locationName: "Nagytétényi út 37-43, 1222 Budapest (C.C. Campona)",
    googleMapsQuery: "Tropicarium Oceanarium Budapest Nagytétényi út",
    tip: "Los jueves a las 15:00 horas se puede presenciar la alimentación directa de los tiburones por submarinistas dentro del tanque principal."
  },
  {
    title: "Zoológico y Jardín Botánico de Budapest",
    originalName: "Fővárosi Állat- és Növénykert",
    category: "cultura",
    description: "Uno de los zoológicos más antiguos y bellos del mundo, inaugurado en 1866 (4,5★ con 49.370 reseñas). Pabellones históricos de estilo Art Nouveau húngaro decorados con cerámica Zsolnay.",
    visited: false,
    priority: "recomendado",
    estimatedTimeMinutes: 120,
    locationName: "Állatkerti krt. 6-12, 1146 Budapest",
    googleMapsQuery: "Budapest Zoo and Botanical Garden Városliget",
    tip: "No te pierdas la Casa del Elefante de estilo oriental ni la Puerta Principal con sus esculturas de osos y elefantes tallados en piedra."
  },
  {
    title: "Mirage Medic Hotel",
    originalName: "Mirage Medic Hotel",
    category: "pest",
    description: "Hotel boutique de 4 estrellas en una villa señorial del siglo XIX (4,4★ con 653 reseñas). Situado en la entrada de la Plaza de los Héroes y el Parque Városliget.",
    visited: false,
    priority: "opcional",
    estimatedTimeMinutes: 20,
    locationName: "Dózsa György út 88, 1068 Budapest",
    googleMapsQuery: "Mirage Medic Hotel Budapest Dózsa György út",
    tip: "Ubicación inmejorable en la avenida Dózsa György para hacer una parada o alojarse cerca de las principales atracciones culturales."
  }
];
